### ISSUE TITLE
Installations can delete /tmp/sensu_server_loaded_files, causing handlers to silently fail

### ISSUE THREAD

**Issue by hashbrowncipher** [sensu/sensu-settings#21]
Handlers require /tmp/sensu_server_loaded_files in order to operate, but many installations prune files from /tmp.  The Filesystem Hierarchy Standard states: "Programs must not assume that any files or directories in /tmp are preserved between invocations of the program", and also "data stored in /tmp may be deleted in a site-specific manner".

The default setting of tmpwatch (as distributed for Ubuntu Trusty) is to delete files when they are thirty days (measured via mtime).  Yelp configures this threshold lower, to ten days. When the file is eventually removed, all Sensu handlers begin to fail. The only way to detect this failure is to monitor the Sensu server error log, using some monitoring framework other than Sensu.  The error message appears as "No such file or directory - /tmp/sensu_server_loaded_files (Errno::ENOENT)"

I can think of three ways to remedy this issue:
1. recreate (or simply touch) the file each time a handler is spawned
2. pass the same data via a pipe.  The file descriptor number for the spawned handler to read from would be passed as /dev/fd/<num> in an environment variable or command-line argument.
3. require the system administrator to configure a directory for Sensu to write temporary state into, which will not be automatically cleaned. (an extra step; rather annoying)
4. a variant of 3, continue to use TMPDIR for temporary state, and document that Sensu requires a TMPDIR which is not automatically cleaned (easy to overlook).

**Comment by bobtfish** [comment]
4 - I think you mean *not* automatically cleaned?

**Comment by hashbrowncipher** [comment]
Yes. I've edited the description, thanks.

**Comment by portertech** [comment]
Just merged https://github.com/sensu/sensu-settings/pull/20 - Sensu 0.22 will include this environment variable, configurable through `/etc/default/sensu`.

**Comment by Gillingham** [comment]
#20 doesn't seem to be taking affect,
```
cat /etc/default/sensu
EMBEDDED_RUBY=true
SENSU_LOADED_TEMPFILE_DIR=/var/run/sensu
```

Yet the files still get created under /tmp and not under /var/run/sensu

**Comment by portertech** [comment]
@Gillingham try `export TMPDIR=/var/run/sensu` in `/etc/default/sensu`.

**Comment by Gillingham** [comment]
@portertech that seems to have resolved it, TMPDIR should probably be in the sensu docs somewhere, doing a google for sensu TMPDIR doesn't result in any really relevant hits outside of #20

**Comment by alex-leonhardt** [comment]
FWIW, just

```TMPDIR=/var/run/sensu``` in ```/etc/default/sensu``` does the trick

thanks!
