### ISSUE TITLE
Provide context for "handlers must be a hash" error

### ISSUE THREAD

**Issue by nhooey** [sensu/sensu-settings#22]
The error ["handlers must be a hash"](https://github.com/sensu/sensu-settings/blob/master/spec/validator_spec.rb#L23) doesn't tell the user in which file this needs to happen. It would be helpful if it provided more context.

There are other similar errors "X must be a Y" that would also be improved with the same idea.

**Comment by portertech** [comment]
@nhooey the `"handlers": {}` definition scope can be in one or more configuration files. All configuration files are deep merged. We recently documented general configuration - https://sensuapp.org/docs/0.21/configuration :+1:
