### ISSUE TITLE
Invalid Gem v3.3.0 test suite

### ISSUE THREAD

**Issue by paramite** [sensu/sensu-settings#25]
Test suite shipped within gem v3.3.0 is missing following symlinks, which made tests to fail:

spec/assets/conf.d/alternative
spec/assets/alternative/conf.d/loop

**Comment by portertech** [comment]
There must be an issue with your git config etc, as the specs pass on Travis CI.

**Comment by paramite** [comment]
What has git config etc. to do with gem :) ? Gem shipped by you is [1] missing symlinks stated above. Just check the gem itself. Please note that I noticed that newer version of the gem contain those symlinks indeed, but are invalid, so when you try to run test suite extracted from gem, it still fails due to the same problem. 

[1] https://rubygems.org/downloads/sensu-settings-3.3.0.gem
