### ISSUE TITLE
Application-independent settings

### ISSUE THREAD

**Issue by dieb** [sensu/sensu-settings#3]
I was wondering if it would be interesting for this gem to not include sensu-specific variables and code. For instance, https://github.com/sensu/sensu-settings/blob/master/lib/sensu/settings/loader.rb#L63 does load some stuff from the env, but that sounds very application-specific.

An alternative to this would be to add the hash setter

```ruby
def []=(key, value)
  @settings[key] = value
end
```

which one could use to set application-specific defaults (on the application itself):

```ruby
@settings = Sensu::Settings.get(options)
@settings[:rabbitmq] = ENV['RABBITMQ_URL'] if ENV['RABBITMQ_URL']
...
```

**Comment by portertech** [comment]
@dieb this library is only intended to serve Sensu core, providing a very simple API to settings loaded from various sources. I'm not really interested in moving setting loading logic back into the services.
