### ISSUE TITLE
Add ability to specify `filters` for extension handlers in configuration

### ISSUE THREAD

**Issue by nhooey** [sensu/sensu-settings#30]
Currently Sensu doesn't allow specifying a `handler` of type `extension`, and therefore can't read a `filters` property in an extension handler's configuration.

So, something like this will fail with "unknown handler type":
```json
{
  "handlers": {
    "sample-extension-handler": {
      "type": "extension",
      "filters": ["sample-extension-filter"]
    }
  }
}
```

Currently it seems the only way to do this is by setting a `filters` property taken from the extension handler's custom named configuration.

**Comment by portertech** [comment]
Handler extension filters are defined in `definition()`.

**Comment by nhooey** [comment]
@portertech Are you talking about this [member variable of an extension handler](https://github.com/sensu/sensu-extensions/blob/e5fda3384c6223fcacc8a0b1e09ca3dfffbb8d21/spec/loader_spec.rb#L26)?

In this case, the extension handler can have `filters` defined in the extension handler code itself, but where can I define `filters` in the JSON configuration?

I'd like to have the extension handler code be static, but have the list of filters applied to events sent to that handler dynamic by configuring them in the JSON configuration. How can I make JSON configuration for an extension handler as shown in the description of this issue?

**Comment by nhooey** [comment]
It makes sense to decouple the `filters` configuration of an extension handler from the actual code implementing that extension handler.

In my case, the `opsgenie` extension handler doesn't know that the `ttl-keepalive-filter` extension filter is installed, but the user will know this and should configure it in the JSON.

All handlers should be completely configurable by JSON config, not just non-extension handlers.

@portertech, @calebhailey

**Comment by calebhailey** [comment]
We're going to try to (finally) get some extension documentation out this week, which should help clarify some of this. I'll update this ticket as soon as that documentation is available and see if it helps clarify things.

**Comment by nhooey** [comment]
@calebhailey Do you have that extension handler documentation yet?

**Comment by nhooey** [comment]
@calebhailey @portertech Given the new [Sensu Extensions documentation](https://sensuapp.org/docs/0.25/reference/extensions.html), how would you add a `filter` to an Extension Handler?

**Comment by calebhailey** [comment]
@nhooey we just scheduled this into our sprint for this week (to document how to configure an extension, with examples).

**Comment by nhooey** [comment]
It looks like you made an issue for the check extension documentation here: sensu/sensu-docs/issues/189, and the actual functionality to make check extensions configurable was merged to `master` in this pull request: sensu/sensu/pull/889.
