### ISSUE TITLE
Unable to restart sensu with broken sym links in config dir

### ISSUE THREAD

**Issue by nishlo** [sensu/sensu-settings#56]
With previous versions of Sensu we were able to restart Sensu with broken sym links in the configuration directory. Since updating to latest Sensu, it seems broken sym links causes start up / restart to fail:
`{"timestamp":"2017-01-03T11:18:29.588747-0600","level":"fatal","message":"config file does not exist or is not readable","file":"/etc/sensu/conf.d/moons.json"}`

I traced this to loader.rb and can restore the previous behaviour by commenting out these lines:
`elsif must_exist`
          `load_error("config file does not exist or is not readable", :file => file)`

This was quite a handy 'feature' which we used to easily decommission application instances.
We used Ansible to deploy our application instance and together with a Sensu config file with the subscription for that instance. This Sensu config file then got sym linked back into /etc/sensu/conf.d.
Here's another person that did the same thing:
http://roobert.github.io/2015/11/09/Sensu-What/

1. Would you consider a pull request to re-enable the previous 'feature'? 
2. Currently i'll have to patch loader.rb on every Sensu client to regain the old functionality. Can you suggest a better way? Maybe there's an override i could use?

**Comment by portertech** [comment]
@nishlo Sensu, as of 0.24, uses consistently strong validation in order to ensure a healthy running state, see https://github.com/sensu/sensu/issues/1244 for the public discussion and https://sensuapp.org/docs/0.24/overview/changelog.html#core-v0-24-0 for the implemented changes.
