### ISSUE TITLE
Socket.gethostname returns FQDN in RHEL 7

### ISSUE THREAD

**Issue by sureshsubramaniam** [sensu/sensu-settings#61]
When the sensu client json does not have a name and ip address defined, sensu overrides from the loader.rb with the ruby Socket.Gethostname, however this returns shortname in the RHEL 6.x and FQDN in the RHEL 7. If we can ensure to always have a shortname for the name, it would be great. If some host provides FQDN and some with shortname it would be misleading in the dashboard or in the api query

**Comment by portertech** [comment]
`Socket.gethostname` is intended as a sensible fallback, if a Sensu client name has not been configured by configuration management. It's still best to have something like Chef or Puppet set the Sensu client name.
