### ISSUE TITLE
Read configuration from key-value store

### ISSUE THREAD

**Issue by keyboardscience** [sensu/sensu-settings#82]
It would be really nice to be able to read configuration from a key-value store since managing JSON files on the server/api host is cumbersome and difficult to manage in large teams.

**Comment by portertech** [comment]
Not implementing in Sensu 1.x, as the Sensu 2.0 Go rewrite uses its API for all configuration (embedded etcd). The Sensu 2.0 Beta will be released in Q1 of 2018 (February). The related software repositories will also become public 🎉
